Fix some build issues on Haiku.
Link with two additional libraries if required.  Do not include
<netinet/if_ether.h>, which does not exist, and which the source does
not require to compile.  These changes allow tcpreplay to build on
Haiku hrev57588 as follows:

./configure --with-libpcap=/path/to/libpcap/ --enable-static-link

However, since Haiku ports do not have GNU AutoGen, the master branch
would need some files either copied from the 4.4.4 release tarball or
generated on a Linux host.  Even after the build completes, tcpreplay
is still not entirely functional because libpcap on Haiku does not
implement pcap_inject() and tcpreplay fails to handle Haiku interfaces
correctly:

> ./src/tcpreplay --listnics
Available network interfaces:
/dev/net/ipro1000/1
vale:/dev/net/ipro1000/1
netmap:/dev/net/ipro1000/1
/dev/net/ipro1000/0
vale:/dev/net/ipro1000/0
netmap:/dev/net/ipro1000/0
> ./src/tcpreplay -i /dev/net/ipro1000/1 icmp-echoreply.pcap

Fatal Error: failed to open device /dev/net/ipro1000/1: error opening
  khial device: Device/File/Resource busy

So proper Haiku support would require some more work.