include ARP HRD type for GRE over IP
I was trying to replay some GTP packets  and I simply wanted to rewrite the L2 Addresses in the packets to match that of the lab devices but the captures were missing L2 ethernet headers and were taken as Linux Cooked Packets aka LINUX_SLL. 
Since there are no pre-existing L2 headers we get the below error:

Fatal Error: From plugins/dlt_linuxsll/linuxsll.c:dlt_linuxsll_decode() line 194:
DLT_LINUX_SLL pcap's must contain only ethernet or loopback packets
We figured out that the link layer address type is GRE over IP 778, we simply defined it under ARPHRD here